# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 22769f682d3e76e89eb598d846568b0dc4f15608f624f4330ca55ee7413b41ba50d1c3098fd81aa1e50c9da26d6939a703136aa2543f356f26816c774c8c7c2b

test:
  secret_key_base: e9f73ec1b4ca8e6815f93b899fb911b9f5b6803d5099b08b51d5652cefc052418d4694684179e20f04763cb70ca9c0f625e83fbc751344532ca85011d6484c56

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
